frontend:
    resource: "@CvBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '.'
    type:     'api_platform'
    prefix: '/api'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
