resources:
  CvBundle\Entity\Message: ~
  CvBundle\Entity\User:
    attributes:
      normalization_context:
        groups: [ "user", "user-read" ]
      denormalization_context:
        groups: [ "user", "user-write" ]
