backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
    methods: ['GET', 'POST']

message_delete:
    path:     /message/{id}/delete
    defaults: { _controller: "BackendBundle:Default:delete" }
    methods:  DELETE