CvBundle\Entity\User:
  type:  entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    fullname:
      type: string
      length: 255
      nullable: true
